import Image from 'next/image'
import React from 'react'

const About = () => {
  return (
    <>
      <section className='about py-5'>
        <div className='container'>
          <div className='row'>
            <div className='col-sm-4'>
              <div className='row img_margin'>
                <div className='col-sm-12'>
                  <div className='img_circle'>
                    <Image src="/web.png" className='image_design img-fluid' height={200} width={200} alt='' />
                  </div>
                </div>
              </div>
            </div>
            <div className='col-sm-8 about_des p-4'>
              <div className='row'>
                <div className='col-sm-12'>
                  <h2 className='font_design'>About Us</h2>
                  <p className='para'>I am Priyanshu Maurya, a passionate Web Developer with expertise in frontend development, MERN stack. I have hands-on experience in building interactive and responsive web applications, including projects like Certificate Verification System, Event Management Platform and Protfolio websites.

                    With a strong foundation in React.js, Node.js, MongoDB, and Express.js, I enjoy developing scalable and efficient applications.

                    Currently, I am expanding my knowledge through real-world projects and internships, always eager to learn new technologies and enhance my problem-solving skills. My short-term goal is to secure a position in a well-esteemed organization, while my long-term ambition is to excel in the field of web development and contribute to innovative projects.

                    I am open to freelance opportunities, collaborations, and full-time roles where I can leverage my skills to build impactful solutions.💡Skills: MERN Stack, React.js, Node.js, Express.js, MongoDB, JavaScript, CSS, API Integration.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default About
export const metadata = {
  title: "About",
  description: "Generated by create next app",
};